name: Tag-Driven Release & Container Build

on:
  push:
    tags:
      - 'v*.*.*'

# Grant the token rights to push packages
permissions:
  contents: write       # allow writing to the repository
  packages: write       # allow writing to ghcr.io

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Docker image:  
            `ghcr.io/${{ github.repository }}:${{ github.ref_name }}`  
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
